CREATE SEQUENCE IF NOT EXISTS seq_pessoa_id
	INCREMENT 1
		NO MAXVALUE
			START WITH 1;

CREATE SEQUENCE IF NOT EXISTS seq_gasto_id
	INCREMENT 1
		NO MAXVALUE
			START WITH 1;

CREATE TABLE IF NOT EXISTS PESSOA (
  ID integer NOT NULL DEFAULT nextval('seq_pessoa_id'),
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  CPF VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS GASTO (
  ID integer NOT NULL DEFAULT nextval('seq_gasto_id'),
  PESSOA_ID INTEGER NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  DTHOUR TIMESTAMP NOT NULL,
  VALUE DECIMAL(9,2) NOT NULL,
  TAGS TEXT,
  PRIMARY KEY (ID),
  CONSTRAINT fk_pessoa FOREIGN KEY (PESSOA_ID) REFERENCES PESSOA (ID) ON DELETE CASCADE ON UPDATE CASCADE
);